name: cicd

on:
#  workflow_dispatch:
  push:
    branch:
      - main
      
jobs:

  code:
    runs-on: ubuntu-latest
    steps:
      - name: Copy the code from github to runner vm
        run: echo "Copy the code from github to runner vm"


  build:
    needs: [code]
    runs-on: ubuntu-latest
    steps:
      - name: Build the docker image form the code
        run: echo "Build the docker image"

  test:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Test the code everthing working or not
        run: echo "Test the code"

  deploy:
    needs: [test]
    runs-on: ubuntu-latest
    steps:  
      - name: deploy the code
        run: echo "Deploy the code on server"
